6) Data Analytics III
1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall on
the given dataset.

In [2]:
# Importing Libraries
import numpy as np
import pandas as pd
from pathlib import Path

In [5]:
# Load the dataset
BASE_DIR = Path().resolve().parent
DATASET_PATH = BASE_DIR / 'DS' / 'datasets' / 'Iris.csv'
df = pd.read_csv(str(DATASET_PATH))

In [6]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
df.replace(["Iris-setosa","Iris-versicolor","Iris-virginica"],[1,2,3], inplace=True)
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        1
1   2            4.9           3.0            1.4           0.2        1
2   3            4.7           3.2            1.3           0.2        1
3   4            4.6           3.1            1.5           0.2        1
4   5            5.0           3.6            1.4           0.2        1

In [9]:
#Spliting the dataset in independent and dependent variables
x = df.iloc[:,:4]
y = df["Species"].values

In [10]:
x.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm
0   1            5.1           3.5            1.4
1   2            4.9           3.0            1.4
2   3            4.7           3.2            1.3
3   4            4.6           3.1            1.5
4   5            5.0           3.6            1.4

In [11]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [12]:
# Splitting the dataset into the Training set and Test set
# We will use 80% of the data for training and then test our model on the 20% held out for that purpose. 
# Scikit-learn contains a function that will randomly split the dataset for us into training and test sets. 

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [13]:
# Use Gaussian NB to create model

from sklearn.naive_bayes import GaussianNB
gaussian= GaussianNB()

In [14]:
gaussian.fit(x_train,y_train)

GaussianNB()

In [15]:
# predicting the test set results
y_pred = gaussian.predict(x_test)
y_pred

array([3, 3, 1, 3, 3, 3, 2, 1, 2, 2, 3, 2, 3, 1, 1, 3, 1, 3, 1, 2, 1, 2,
       2, 3, 1, 3, 1, 1, 2, 2])

In [16]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y_test, y_pred)
cm

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [17]:
print('true negatives (TN):  ', cm[0,0])
print('true positives (TP):  ', cm[1,1])
print('false positives (FP): ', cm[0,1])
print('false negative (FN):  ', cm[1,0])

true negatives (TN):   10
true positives (TP):   9
false positives (FP):  0
false negative (FN):   0


In [18]:
from sklearn.metrics import accuracy_score ,precision_score,recall_score
accuracy = accuracy_score(y_test,y_pred)
precision =precision_score(y_test, y_pred,average='micro')
recall =  recall_score(y_test, y_pred,average='micro')

In [19]:
print("Accuracy: ",accuracy)
print("Precision: ",precision)
print("Recall: ",recall)

Accuracy:  1.0
Precision:  1.0
Recall:  1.0


In [20]:
cl_report=classification_report(y_test,y_pred)
print(cl_report)

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         9
           3       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

